#! /bin/sh

# Keep average/min/max for:
#   15 minutes for 1 month (3000 *   1 * 15 minutes)
#    1 day for 1 year      (366  *  96 * 15 minutes)
#    1 week for 20 years   (1040 * 672 * 15 minutes)
rrdtool create pv.rrd    \
 --step 900                       \
 DS:watthour:ABSOLUTE:3600:0:65536 \
 RRA:AVERAGE:0.5:1:3000            \
 RRA:AVERAGE:0.5:96:740            \
 RRA:AVERAGE:0.5:672:2100          \
 RRA:MIN:0.5:1:3000                \
 RRA:MIN:0.5:96:366                \
 RRA:MIN:0.5:672:1040              \
 RRA:MAX:0.5:1:3000                \
 RRA:MAX:0.5:96:366                \
 RRA:MAX:0.5:672:1500


