PROJNAME=sensor_gateway
DEVICE=CY8C29566
BASEDEVICE=CY8C29000
PROJPATH=D:/hollevo/projects/personal/hasy/oswald/firmware/SENSOR~1/SENSOR~1
PSOCDIR=C:/PROGRA~1/Cypress/Common/CYPRES~2
INCLUDE_PATH=C:/PROGRA~1/Cypress/Common/CYPRES~2/tools/include/CY8C29~1
CSRCS= main.c oo.c shtxx.c
LIBCSRCS=
ASMSRCS=
LIBASMSRCS= counter8_ltrx.asm counter8_ltrxint.asm led1.asm ltrx.asm ltrxint.asm ltrxplus.asm onewire.asm onewireint.asm psocconfig.asm psocconfigtbl.asm ticker.asm tickerint.asm
OBJECT_SOURCES= main.c oo.c shtxx.c
FILLVALUE=0x30
LASTROM=0x7fff
HI-TECHDIR=C:\PROGRA~1\HI-TEC~1\HCPSOC\PRO\9.61
LASTRAM=0x7ff
MORE_CFLAGS=--WARN=0  --OPT=asm,9 
CDEFINES=
LIBS=
LIB_PATH=
SYS_INC_CONTENTS:=IMAGECRAFT:_equ_1 HITECH:_equ_2 TOOLCHAIN:_equ_HITECH SYSTEM_LARGE_MEMORY_MODEL:_equ_1 SYSTEM_SMALL_MEMORY_MODEL:_equ_0 SYSTEM_STACK_PAGE:_equ_7 SYSTEM_STACK_PAGE_OFFSET:_equ_0 
SYSTEM_TOOLS=2
CONFIG_NAMES=temp_humi_logger temp_humi_logger temp_humi_logger temp_humi_logger temp_humi_logger temp_humi_logger sensor_gateway sensor_gateway sensor_gateway sensor_gateway sensor_gateway sensor_gateway sensor_gateway sensor_gateway sensor_gateway sensor_gateway sensor_gateway sensor_gateway sensor_gateway sensor_gateway sensor_gateway sensor_gateway sensor_gateway sensor_gateway sensor_gateway sensor_gateway sensor_gateway sensor_gateway 
