#!/bin/bash 

if [ -n "$1" ]
then
   echo "Requesting state for circle $1..."
   xpl-sender -c plugwise.basic -m xpl-cmnd command=status device=$1 -w 3
else
   echo "Please pass the cicrle id to set on";
fi

