PROJNAME=wireless_gateway
DEVICE=CY8C29566
BASEDEVICE=CY8C29000
PROJPATH=D:/hollevo/projects/personal/home/oswald/firmware/WIRELE~1/WIRELE~1
PSOCDIR=C:/PROGRA~1/Cypress/Common/CYPRES~3
INCLUDE_PATH=C:/PROGRA~1/Cypress/Common/CYPRES~3/tools/include/CY8C29~1
CSRCS= main.c
LIBCSRCS=
ASMSRCS=
LIBASMSRCS= counter8.asm counter8_ltrx.asm counter8_ltrxint.asm counter8int.asm led1.asm ltrx.asm ltrxint.asm ltrxplus.asm psocconfig.asm psocconfigtbl.asm ticker.asm tickerint.asm uart_in.asm uart_inint.asm uart_inplus.asm
OBJECT_SOURCES= main.c
FILLVALUE=0x30
LASTROM=0x7fff
LASTRAM=0x7ff
LAST_DATARAM=0x6ff
CODECOMPRESSOR=
MORE_CFLAGS=-Wf-Osize -Wf-LMM8 -D_LMM
RELSTART=0x1a0
CDEFINES=
LIBS=
UMLIBS=
LIB_PATH=
ENABLE_ALIGN_SHIFT=0
LMM=1
SYS_INC_CONTENTS:=SYSTEM_STACK_PAGE:_equ_7 SYSTEM_STACK_BASE_ADDR:_equ_0h SYSTEM_LARGE_MEMORY_MODEL:_equ_1 SYSTEM_SMALL_MEMORY_MODEL:_equ_0 IMAGECRAFT:_equ_1 HITECH:_equ_2 TOOLCHAIN:_equ_IMAGECRAFT 
SYSTEM_TOOLS=1
CSFLOW=
CONFIG_NAMES=wireless_gateway 
