/******************************************************************************
*  Generated by PSoC Designer 5.0.1127.0
******************************************************************************/
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "Counter8.h"
#include "Counter8_ltrx.h"
#include "LED1.h"
#include "LTRX.h"
#include "Ticker.h"
#include "UART_IN.h"

#endif
