#! /bin/sh

# Keep average/min/max for:
#   30 minutes for 1 month (1500 *   1 * 30 minutes)
#    1 day for 1 year      (366  *  48 * 30 minutes)
#    1 week for 20 years   (1040 * 336 * 30 minutes)
rrdtool create pv.rrd    \
 --step 1800                       \
 DS:watthour:ABSOLUTE:1800:0:65536 \
 RRA:AVERAGE:0.5:1:1500            \
 RRA:AVERAGE:0.5:48:366            \
 RRA:AVERAGE:0.5:336:1040          \
 RRA:MIN:0.5:1:1500                \
 RRA:MIN:0.5:48:366                \
 RRA:MIN:0.5:336:1040              \
 RRA:MAX:0.5:1:1500                \
 RRA:MAX:0.5:48:366                \
 RRA:MAX:0.5:336:1500


