;;*****************************************************************************
;;*****************************************************************************
;;  FILENAME: OneWireINT.asm
;;   Version: 1.1, Updated on 2009/10/15 at 17:11:37
;;  Generated by PSoC Designer 5.0.1127.0
;;
;;  DESCRIPTION: OneWire Interrupt Service Routine
;;
;;-----------------------------------------------------------------------------
;;   Copyright (c) Cypress Semiconductor 2009. All Rights Reserved.
;;*****************************************************************************
;;*****************************************************************************

include "m8c.inc"
include "OneWire.inc"


;-----------------------------------------------
;  Global Symbols
;-----------------------------------------------
export  _OneWire_ISR

AREA UserModules (ROM, REL)

;-----------------------------------------------------------------------------
;  FUNCTION NAME: _OneWire_ISR
;
;  DESCRIPTION: With ParasitePower enabled this ISR sets TX pin to strong
;               drive mode immediately after transmission of last data bit.
;-----------------------------------------------------------------------------

_OneWire_ISR:
IF (OneWire_PARASITE_ENABLE)
    M8C_SetBank1
    and   REG[OneWire_OUT_PORT_DM1],~OneWire_OUT_PORT_MASK
    M8C_SetBank0
ENDIF
   reti

; end of file OneWireINT.asm
